### ISSUE TITLE
Visual design improvements

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/ETHPrize#6]
**Overall color scheme**
The color combination of red and blue is very tiring to read for a number of reasons: 
1. the colors themselve (red and blue) are a bad combination. 
2. both are dark, they have little contrast 
3. they are filled with a pattern 
4. they are shown on a patterned background. 

My suggestion is to:
- Reconsider the color scheme (hues and contrast), 
- Keep titles plain and use the patterned background for example in the header only.

**Section overlay**
I like the effect that the sections come up at the same position as you scroll. But, I find it difficult to distinguish the top layer from the page background. For example I thought I could select Show more, but I can't this is a button on the page background, not the overlay.
The reasons for this: 
1. low contrast. 
2. only rows have a filled background, 'breaking the overlay' and making my eyes go front to back over and over. 

I suggest to:

- Use a full section background, rather than row-by-row, including the Title on this background. 
- Consider the color scheme (hue, contrast, and transparency of the section background). Ideally the section background is of a lighter hue than the full page background and has a transparency close to 0.
- Making the width of the About section the same as the other sections would improve consistency.

**Comment by andytudhope** [comment]
@fshkliarau @denis-sharypin we can make this into a small bounty issue if you agree with some of the feedback and have a bit of time this week to work on it?

**Comment by fshkliarau** [comment]
Hey Andy,
Sure, I can work on this but I won’t have time until Thursday. Let me know if it works for you timewise.

**Comment by andytudhope** [comment]
Sure thing, Thursday is fine 👍

**Comment by andytudhope** [comment]
We are also wanting to add more detail that will pop up in a modal when you click `Learn More` on either of those bounties. Content is in [here](https://docs.google.com/document/u/1/d/1z7Jq4n6gTaE_Xw2U4liXoPH0oJWCjTfHwcfNh-ej0yw/edit). 

So we can add that to the list of TODOs to start on Thursday too 😉

**Comment by denis-sharypin** [comment]
@hesterbruikman  Thanks for your time.
Probably we can improve the contrast between headings and a background, thanks for suggestions.
@fshkliarau  could you use this [tool](https://webaim.org/resources/contrastchecker/) to find a good color match, please?

And in general, this kinda of websites I believe could have small weirdnesses since it's a promo website and it affects more on the emotional part of users than rational.

@andytudhope could we set up a small bounty then for this?

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x51bd17602d7a1cf63f244995348990d4bb5437b297b28b42bae1614b14df3853](https://etherscan.io/tx/0x51bd17602d7a1cf63f244995348990d4bb5437b297b28b42bae1614b14df3853)

**Comment by fshkliarau** [comment]
Hey guys, thanks for the feedback, the update can be found in the [Figma file](https://www.figma.com/file/FCakALK84WSxZB5QhvaV213e/ETHPrize?node-id=1%3A2)

**Comment by andytudhope** [comment]
Will you submit a no-op PR @fshkliarau, or one that just adds that new link to the README and contains the text `Fixes #6` so that I can merge it and pay out the bounty? Really nice work!

@CS76 any chance you could make the changes here to the colours, headings, and pop up modals when clicking `Learn more` on each bounty? I will of course create an issue and small bounty for the work.

**Comment by andytudhope** [comment]
Hi @fshkliarau - that does not work. You need to please  submit an actual Pull Request that has the text `Fixes #6` in it in order for the system to pick your contribution up and pay you when I merge this.

**Comment by andytudhope** [comment]
@fshkliarau ?? Will you submit that PR please?
